### ISSUE TITLE
OnPlayerConnect SQL Error

### ISSUE THREAD

**Issue by pimpmyname2** [CSSPanel/Plugin#3]
CSS-Panel) An error occurred in OnPlayerConnect: Cannot implicitly convert type 'string' to 'int'

**Comment by crashzk** [comment]
I believe it is related to the issue https://github.com/CSSPanel/Plugin/issues/5 as well.

**Comment by crashzk** [comment]
Test the latest version of CSS Panel & Plugin, it solved the problem for me.

I believe you can close this issues.
